name: Build and push Docker image

on:
  push:
    branches:
      - none #master
      
  workflow_dispatch:    
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: team6-redash
      IMAGE_TAG: devOps
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: COnfigure Docke Client
        run: |-
            gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

            
        #Gotta change the line below
      - name: Build Docker image
        run: |
          docker build -t us-west2-docker.pkg.dev/terraform-project-serbianum/team6-redash-docker/${{ env.IMAGE_NAME }} .
        #LOCATION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-west2-docker.pkg.dev/terraform-project-serbianum/team6-redash-docker/${{ env.IMAGE_NAME }}